### PR TITLE
make includeTrashed configurable

### PR DESCRIPTION
**Pull request by cboulanger**
The sync code hardcodes the synchronization of trashed items. This makes this a configurable setting, with a default of "false", which arguably is what I think is expected.

### CODE REVIEW

**Comment by retorquere** [comment]
Agreed on making it configurable, disagree on making it the default; collections for example will still refer to trashed items and with a default of false you'd have collections with non-existent items.

**Comment by cboulanger** [comment]
I did not know collections still contain trashed items - I thought if you trash it, it gets removed from any collection? Anyways, I  changed the default to true.

**Comment by cboulanger** [comment]
oops, regression here, this somehow reverted my other PR. Just a minute...

**Comment by cboulanger** [comment]
Ok, fixed. Ready for merge.

**Comment by retorquere** [comment]
They don't show in collections in Zotero, bu if you restore an item from the trash, it reappears in the collections it was in. Zotero remembers them as part of the collection until they are purged.

**Comment by cboulanger** [comment]
I see. Thanks.

**Pull request merged**
