### PR TITLE
Add the "type" property to the Library interface

### PR DESCRIPTION
**Pull request by cboulanger**
otherwise I get an error when trying to query it.

### CODE REVIEW

**Comment by retorquere** [comment]
I'd be OK with giving you collab access to the repo BTW. I'm not sure I can grant npm publishing rights -- as far as I know, that is tied to my account.

**Comment by retorquere** [comment]
Wait -- why are you getting errors? Library is an interface, it should give no errors when you extend it.

**Comment by cboulanger** [comment]
Oh as long as you don't mind merging my PRs I think we can keep on doing this - it is good if the PRs get reviewed.

**Comment by retorquere** [comment]
The JSON store adds a number of properties beyond what `Library` specifies and that doesn't give me any problems.

**Comment by cboulanger** [comment]
In
```javascript
    syncEngine.on(Sync.event.library, (library: Zotero.Library, index: number, total: number) => {
        let name = library.type === "group" ? library.name : "User library";
        gauge.show(`Saving library "${name}" (${index}/${total})`, index/total);
    });
```
it wouldn't let me do the ` let name = library.type === "group" ...` comparison otherwise. It might be nonsense to type the event handling function arguments, but I kind of got into the habit now...

**Comment by retorquere** [comment]
Ah, OK -- you'd have to change that to

```
syncEngine.on(Sync.event.library, (library: <your library type>, index: number, total: number) => {
        let name = library.type === "group" ? library.name : "User library";
        gauge.show(`Saving library "${name}" (${index}/${total})`, index/total);
    });
```

**Comment by retorquere** [comment]
Buuuut, I take your point that the stored library should know its type. Forget what I said earlier. But then, `.get` should also be changed.

**Comment by retorquere** [comment]
Hum. But then it stands to reason it should also know it's prefix.

**Comment by cboulanger** [comment]
The prefix would of course suffice for determining the type. You decide ... both is better than name: undefined

**Comment by retorquere** [comment]
Torn on this one. The user_or_group_prefix is used everywhere in the api docs, so it makes some sense as an opaque identifier. On the other hand, it's clearly derived from type + id, so we're passing around redundant information. Not a big fan of that. If you find a library that has type `group` but a prefix `user`, that would make no sense.

Leaning towards just removing the prefix everywhere. It's really more a Zotero API thing. The identifier is type + id, not specifically how they're formatted in API calls.

**Comment by cboulanger** [comment]
All fine with me  - I just need the final API so I can update my test code.

**Comment by cboulanger** [comment]
I see now that my last "type" PR created all kind of problems down the line. I would have had to mark it as opional to make it work with the existing store implementations.

**Comment by retorquere** [comment]
I'm going to stick with prefix -- having a two-part key really makes the library a ton more complex and I don't think that is warranted for something as simple as this. You can infer the type from the prefix, or you can just test on `.startsWith('/group')`. WRT the emitter handlers, https://github.com/retorquere/zotero-sync/pull/7#issuecomment-824155224 will do the job.

**Comment by retorquere** [comment]
We don't actually have to add anything to the interface -- stores are free to add a `type` property when `get` is called, based on the `prefix` being gotten. That way the type is strictly derived from the prefix at a single point, which should make it safe and easy to use.

**Comment by retorquere** [comment]
Gaah but then you can't have type guards because TS only allows type guards on scalars.

**Comment by cboulanger** [comment]
What is emitted is not the Library class but the object that is being set on `this.libraries`. It would be nicer to have the real Library object there but maybe we are spending too much time on this relatively marginal question.

**Comment by cboulanger** [comment]
It's good enough to know that the "prefix" property of this object can be observed.

**Comment by retorquere** [comment]
Yeah but then you can't test whether you can use the `.name` property, and typescript will complain. Having a separate `.type` property will allow TS to infer the type safely.

**Comment by cboulanger** [comment]
this works:
```javascript
    syncEngine.on(Sync.event.library, (library: {prefix: string, type:string, name?: string }, index: number, total: number) => {
        let name = library.type === "group" ? library.name : "User library";
        gauge.show(`Saving library "${name}" (${index}/${total})`, index/total);
    });
```

**Comment by cboulanger** [comment]
Good enough for documentation, maybe.

**Comment by retorquere** [comment]
I've simplified things. There's now just one `RemoteLibrary` type, with a `type` field and as far as I'm concerned an opaque `prefix` identifier.

**Comment by retorquere** [comment]
The `name` for a `user` library is just an empty string. This is still false-ish but you can always do string ops on it.

**Comment by cboulanger** [comment]
Tada again: https://github.com/cboulanger/zotero-sync-bookends

Just a prototype for now, but it works nicely... This can eventually be replicated for all reference managers that allow scripting in some form.

**Comment by cboulanger** [comment]
This is fun - for lack of a more fitting place for sync metadata in Bookends, I am storing it in the titles of the synchronized Bookends "groups" (which correspond to Zotero "libraries" in my implementation): 
Bildschirmfoto 2021-04-23 um 08 23 30

**Pull request merged**
