### PR TITLE
Avoid "undefined" library name for user library

### PR DESCRIPTION
**Pull request by cboulanger**

### CODE REVIEW

**Comment by retorquere** [comment]
The thing is that the user library does not have a fixed name. It is locale dependent. I'd rather signal somehow that this concerns the user library so that it is clear that if a name is to be displayed, it is up to the consumer to think of one.

**Comment by cboulanger** [comment]
Makes sense.  I'll check for undefined in my own code.

**Comment by retorquere** [comment]
I've added a `type` to RemoteLibrary

**Comment by cboulanger** [comment]
Cool. This allows a more robust checking (name could be undefined for many reasons)

**Comment by retorquere** [comment]
It can't, really. Zotero groups always have a name.

Hmmm... instead of the `prefix` + type, we could break the two out; both would have `type` and `id`, and `prefix` would just be `'/${type}/${id}`. The type is otherwise implied by the lead of the prefix.

**Pull request closed without merging**
